steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/infinite-bruin-439311-d5/demo-registry/nginx-demo:$BUILD_ID', '-f', 'Dockerfile', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/infinite-bruin-439311-d5/demo-registry/nginx-demo:$BUILD_ID']
# Deploy container image to Cloud Run

images:
- us-central1-docker.pkg.dev/infinite-bruin-439311-d5/demo-registry/nginx-demo:$BUILD_ID
options:
  logging: CLOUD_LOGGING_ONLY